### PR TITLE
I31: Fix test for stringsAsFactors change

### LINKED ISSUE #31: Fix for R 4.0.0 change in stringsAsFactors behaviour
```
  -- 1. Failure: nse 2 (@test-encrypt-wrapper.R#36) -----------------------------
  decrypt(read.csv(filename), x) not equal to `iris`.
  Component "Species": Modes: character, numeric
  Component "Species": Attributes: < target is NULL, current is list >
  Component "Species": target is character, current is factor
  
  == testthat results ===========================================================
  [ OK: 270 | SKIPPED: 2 | WARNINGS: 0 | FAILED: 1 ]
  1. Failure: nse 2 (@test-encrypt-wrapper.R#36)
```

### PR DESCRIPTION
**Pull request by richfitz**
This PR fixes a test that is failing on R-devel due to the upcoming change to stringsAsFactors

Confirmed failing on r-devel here: https://travis-ci.org/ropensci/cyphr/jobs/655934915?utm_medium=notification&utm_source=github_status

Fixes #31

### CODE REVIEW

File: tests/testthat/test-encrypt-wrapper.R [hunk 1]
```diff
@@ -30,10 +30,12 @@ test_that("nse 2", {
   filename <- tempfile()
   on.exit(file_remove_if_exists(filename))
 
-  encrypt(write.csv(iris, filename, row.names = FALSE), x)
+  d <- data.frame(a = 1:10, b = sample(1:10))
```
Comment (maelle) [inline tests/testthat/test-encrypt-wrapper.R:33]: Why can't it work with iris by changing some arguments? Sorry if I'm missing something obvious.

Comment (richfitz) [reply tests/testthat/test-encrypt-wrapper.R:33]: The message from CRAN suggests adding `stringsAsFactors = TRUE` to `read.csv` and friends to preserve behaviour but only if the order of factors never matters and to make sure tests pass with both `stringsAsFactors` defaults.  I could do that but `iris` *does* have a factor for the `Species` column, so I would have ended up making the test more complicated and fragile.

The aim of this test is to try and roundtrip a csv - no need to get concerned with factors, so I am now just creating a small example with no factor problems.

Comment (maelle) [reply tests/testthat/test-encrypt-wrapper.R:33]: Ok, it makes sense, thank you!

File: CONDUCT.md [hunk 2]
```diff
@@ -10,4 +10,4 @@ Project maintainers have the right and responsibility to remove, edit, or reject
 
 Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by opening an issue or contacting one or more of the project maintainers.
 
-This Code of Conduct is adapted from the Contributor Covenant (http:contributor-covenant.org), version 1.0.0, available at http://contributor-covenant.org/version/1/0/0/
+This Code of Conduct is adapted from the Contributor Covenant (https://contributor-covenant.org), version 1.0.0, available at https://contributor-covenant.org/version/1/0/0/
```
Comment (maelle) [inline CONDUCT.md:13]: Good idea to move to https at the same time!

File: tests/testthat/test-encrypt-wrapper.R [hunk 3]
```diff
@@ -30,10 +30,12 @@ test_that("nse 2", {
   filename <- tempfile()
   on.exit(file_remove_if_exists(filename))
```
Comment (maelle) [inline tests/testthat/test-encrypt-wrapper.R:31]: The test file could include "round trip" in the comments or test names, since current test names are a bit... cryptic :stuck_out_tongue_winking_eye:

**Review by maelle — CHANGES_REQUESTED** [review]

**Review by maelle — APPROVED** [review]
Awesome, no further comment! :ok_hand:
